# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023-2024 Advanced Micro Devices, Inc.
apiVersion: v1
kind: Pod
metadata:
  name: onload-sfnettest-server
  namespace: default
  labels:
    app.kubernetes.io/part-of: sfnettest
    app.kubernetes.io/component: server
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-bond0
spec:
  restartPolicy: Always
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: onload-sfnettest-server
    # The image's default entrypoint is a sfnt-pingpong server
    image: docker.io/onload/sfnettest:1.6.0-rc2
    resources:
      limits:
        amd.com/onload: 1
    envFrom:
      - configMapRef:
          name: onload-latency-profile
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  nodeName: compute-0
---
apiVersion: v1
kind: Pod
metadata:
  name: onload-sfnettest-client
  namespace: default
  labels:
    app.kubernetes.io/part-of: sfnettest
    app.kubernetes.io/component: client
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-bond0
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: onload-sfnettest-client
    image: docker.io/onload/sfnettest:1.6.0-rc2
    command:
    - /bin/sh
    - -c
    - --
    args:
    - "sleep infinity"
    resources:
      limits:
        amd.com/onload: 1
    envFrom:
      - configMapRef:
          name: onload-latency-profile
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  nodeName: compute-1
