# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onload-runtime
resources:
- ../build/
- ../kmm/
- ../cplane/
- ../deviceplugin/

images:
- name: cplane
  newName: image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-user
  newTag: git27b3826
- name: device-plugin
  newName: image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-device-plugin
  newTag: latest
