version: 2
updates:
  - package-ecosystem: gomod
    open-pull-requests-limit: 0 # security only
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: cleanup

  - package-ecosystem: docker
    open-pull-requests-limit: 0 # security only
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: cleanup

  - package-ecosystem: github-actions
    open-pull-requests-limit: 0 # security only
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: cleanup
