# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sfc-module-dockerfile
  namespace: openshift-kmm
data:
  dockerfile: |
    ARG DTK_AUTO
    FROM ${DTK_AUTO} as builder

    ARG KERNEL_VERSION

    WORKDIR /build/

    RUN git clone --depth 1 https://github.com/Xilinx-CNS/onload.git

    WORKDIR /build/onload

    # Currently there are issues regarding when building the sfc driver due to
    # differences between the DTK image used for building and the ubi image used
    # for loading the drivers.
    #
    # Issues found are with:
    # * vdpa
    # * mtd
    #
    # To prevent building the problematic things we have to pass additional
    # parameters to the driver build. Unfortunately it is currently possible to do
    # this with onload's build scripts, so the driver's Makefile is used directly.
    RUN make -j8 -C src/driver/linux_net CONFIG_SFC_VDPA= CONFIG_SFC_MTD= KVER=${KERNEL_VERSION}

    FROM docker.io/redhat/ubi8:latest
    ARG KERNEL_VERSION

    RUN yum -y install kmod && yum clean all
    RUN mkdir -p /opt/lib/modules/${KERNEL_VERSION}
    COPY --from=builder /build/onload/src/driver/linux_net/drivers/net/ethernet/sfc/sfc.ko /opt/lib/modules/${KERNEL_VERSION}/
    COPY --from=builder /build/onload/src/driver/linux_net/drivers/net/ethernet/sfc/sfc_driverlink.ko /opt/lib/modules/${KERNEL_VERSION}/
    RUN /usr/sbin/depmod -b /opt
---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: sfc-module
  namespace: openshift-kmm
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: sfc
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: image-registry.openshift-image-registry.svc:5000/openshift-kmm/sfc-module:latest
          build:
            dockerfileConfigMap:
              name: sfc-module-dockerfile
  selector: # top-level selector
    kubernetes.io/arch: amd64
