# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: sfc-module
  namespace: openshift-kmm
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: sfc
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: image-registry.openshift-image-registry.svc:5000/openshift-kmm/sfc-module:v8.1.0-${KERNEL_FULL_VERSION}
          build:
            dockerfileConfigMap:
              name: sfc-module-dockerfile
            buildArgs:
            - name: ONLOAD_LOCATION
              value: (placeholder)
            - name: DTK_IMAGE
              value: (placeholder)
            - name: UBI8_IMAGE
              value: (placeholder)
  selector: # top-level selector
    kubernetes.io/arch: amd64
