# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "onload.amd.com/v1alpha1",
          "kind": "Onload",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "onload-operator",
              "app.kubernetes.io/instance": "onload-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "onload",
              "app.kubernetes.io/part-of": "onload-operator"
            },
            "name": "onload-sample"
          },
          "spec": {
            "devicePlugin": {
              "devicePluginImage": "image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-device-plugin:latest",
              "imagePullPolicy": "Always"
            },
            "onload": {
              "imagePullPolicy": "Always",
              "kernelMappings": [
                {
                  "kernelModuleImage": "image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-module:v8.1.0-${KERNEL_FULL_VERSION}",
                  "regexp": "^.*\\.x86_64$"
                }
              ],
              "userImage": "image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-user:v8.1.0",
              "version": "8.1.0"
            },
            "selector": {
              "node-role.kubernetes.io/worker": ""
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-08-15T09:06:14Z"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: onload-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Onload is the Schema for the onloads API
      displayName: Onload
      kind: Onload
      name: onloads.onload.amd.com
      statusDescriptors:
      - description: Conditions store the status conditions of Onload
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: manages onload deployments in a cluster
  displayName: onload-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - kmm.sigs.x-k8s.io
          resources:
          - modules
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - onload.amd.com
          resources:
          - onloads
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - onload.amd.com
          resources:
          - onloads/finalizers
          verbs:
          - update
        - apiGroups:
          - onload.amd.com
          resources:
          - onloads/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: onload-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: onload-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: onload-operator
          control-plane: controller-manager
        name: onload-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: kitchen-sink.kube.test:5000/controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: onload-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: onload-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - onload
  links:
  - name: Onload Operator
    url: https://onload-operator.domain
  maturity: alpha
  provider:
    name: AMD
    url: github.com/Xilinx-CNS/kubernetes-onload
  version: 0.0.1
