# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "onload.amd.com/v1alpha1",
          "kind": "Onload",
          "metadata": {
            "name": "onload"
          },
          "spec": {
            "devicePlugin": {
              "imagePullPolicy": "IfNotPresent"
            },
            "onload": {
              "imagePullPolicy": "IfNotPresent",
              "kernelMappings": [
                {
                  "build": {
                    "buildArgs": [
                      {
                        "name": "ONLOAD_BUILD_PARAMS",
                        "value": ""
                      },
                      {
                        "name": "ONLOAD_SOURCE",
                        "value": "docker.io/onload/onload-source:8.1.2.26"
                      }
                    ],
                    "dockerfileConfigMap": {
                      "name": "onload-module-dockerfile-ch29bghg54"
                    }
                  },
                  "kernelModuleImage": "image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-module:8.1.2.26-${KERNEL_FULL_VERSION}",
                  "regexp": "^.*\\.x86_64$",
                  "sfc": {}
                }
              ],
              "userImage": "docker.io/onload/onload-user:8.1.2.26-ubi8",
              "version": "8.1.2.26"
            },
            "selector": {
              "node-role.kubernetes.io/worker": ""
            },
            "serviceAccountName": "onload-operator-sa"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-01-17T09:24:35Z"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: onload-operator.v3.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Onload is the Schema for the onloads API
      displayName: Onload
      kind: Onload
      name: onloads.onload.amd.com
      statusDescriptors:
      - description: Conditions store the status conditions of Onload
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: manages onload deployments in a cluster
  displayName: onload-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - patch
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - delete
          - get
          - list
          - patch
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/eviction
          verbs:
          - create
        - apiGroups:
          - kmm.sigs.x-k8s.io
          resources:
          - modules
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - onload.amd.com
          resources:
          - onloads
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - onload.amd.com
          resources:
          - onloads/finalizers
          verbs:
          - update
        - apiGroups:
          - onload.amd.com
          resources:
          - onloads/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: onload-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: onload-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: onload-operator
          control-plane: controller-manager
        name: onload-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --leader-elect
                command:
                - /manager
                env:
                - name: DEVICE_PLUGIN_IMG
                  value: docker.io/onload/onload-device-plugin:3.0.0
                image: docker.io/onload/onload-operator:3.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: onload-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: onload-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - onload
  links:
  - name: Onload Operator
    url: https://github.com/Xilinx-CNS/kubernetes-onload
  maturity: alpha
  provider:
    name: AMD
    url: https://www.xilinx.com/support/download/nic-software-and-drivers.html#kubernete
  version: 3.0.0
