# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: onload-operator-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onload-operator-role
subjects:
- kind: ServiceAccount
  name: onload-operator-sa
