# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- onload-module.yaml
configMapGenerator:
- name: onload-module-dockerfile
  files:
  - dockerfile=Dockerfile
configurations:
- module-nameref.yaml
