# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onload-kmm-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onload-kmm-role
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onload-kmm-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onload-kmm-role
subjects:
- kind: ServiceAccount
  name: onload-kmm-sa
---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: onload-module
spec:
  moduleLoader:
    serviceAccountName: onload-kmm-sa
    container:
      modprobe:
        moduleName: onload
        parameters:
        - '--first-time'
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: image-registry.openshift-image-registry.svc:5000/onload-artifacts/onload-module:latest
          build:
            dockerfileConfigMap:
              name: onload-module-dockerfile
            buildArgs:
            - name: ONLOAD_BUILD_PARAMS
              value: ""
  selector: # top-level selector
    kubernetes.io/arch: amd64
