# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: onload-module
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: onload
        parameters:
        - '--first-time'
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: image-registry.openshift-image-registry.svc:5000/onload-artifacts/onload-module:latest
          build:
            dockerfileConfigMap:
              name: onload-module-dockerfile
            buildArgs:
            - name: ONLOAD_BUILD_PARAMS
              value: ""
  selector: # top-level selector
    kubernetes.io/arch: amd64
