# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cns-sfnettest.yaml
