# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.

resources:
- ../../base
- ../../onload-module/dtk-ubi

patches:
- path: patch-onload.yaml

images:
#- name: onload/onload-device-plugin
#  newName: docker.io/onload/onload-device-plugin
#  newTag: 3.0.0

- name: onload/onload-source
  newName: docker.io/onload/onload-source
  newTag: 8.1.2.26
- name: onload/onload-user
  newName: docker.io/onload/onload-user
  newTag: 8.1.2.26
- name: onload/onload-module
  newName: image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload/onload-module
  newTag: 8.1.2.26-${KERNEL_FULL_VERSION}
