# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
resources:
- ../../base

patches:
- path: patch-onload.yaml

images:
- name: onload/onload-user
  newName: docker.io/onload/onload-user
  newTag: 8.1.2.26-ubi8

# `onload-source` not used by pre-built images.
# `onload-module` specified in `patch-onload.yaml` with literal string method.
