# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: onload.amd.com/v1alpha1
kind: Onload
metadata:
  name: onload
spec:
  onload:
    kernelMappings:
      # Literal strings example provided here as a method of self-documenting which images have been pre-built.
      # The regular expression & `${KERNEL_FULL_VERSION}` variable method is also supported with pre-built images.
      - regexp: 4.18.0-372.49.1.el8_6.x86_64
        kernelModuleImage: image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-module:8.1.2.26-4.18.0-372.49.1.el8_6.x86_64

        # Deploy `sfc` Module CR in addition to `onload` Module CR.
        # (Incompatible with MachineConfig approach.)
        #sfc: {}
