# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: sfc-module
  namespace: openshift-kmm
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: sfc
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: www.example.com/sfc-module:enterpriseonload-8.1.0.2-${KERNEL_FULL_VERSION}
          build:
  selector: # top-level selector
    kubernetes.io/arch: amd64
