# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
resources:
- ../base
#+kubebuilder:scaffold:manifestskustomizesamples
configurations:
- nameref.yaml

patchesStrategicMerge:
- patch-build.yaml
