# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: onload.amd.com/v1alpha1
kind: Onload
metadata:
  name: onload-sample
spec:
  onload:
    kernelMappings:
      - regexp: '^.*\.x86_64$'
        kernelModuleImage: image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-module:v8.1.0-${KERNEL_FULL_VERSION}
        sfc: {}
        build:
          dockerfileConfigMap:
            name: onload-module-dockerfile
          buildArgs:
          - name: ONLOAD_BUILD_PARAMS
            value: ""
          - name: ONLOAD_SOURCE
            value: "example.com:5000/onload-source:latest"
