# permissions for end users to edit onloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: onload-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: onload-operator
    app.kubernetes.io/part-of: onload-operator
    app.kubernetes.io/managed-by: kustomize
  name: onload-editor-role
rules:
- apiGroups:
  - onload.amd.com
  resources:
  - onloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - onload.amd.com
  resources:
  - onloads/status
  verbs:
  - get
