---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - onload.amd.com
  resources:
  - onloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - onload.amd.com
  resources:
  - onloads/finalizers
  verbs:
  - update
- apiGroups:
  - onload.amd.com
  resources:
  - onloads/status
  verbs:
  - get
  - patch
  - update
