# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onload-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onload-operator-role
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onload-operator-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onload-operator-role
subjects:
- kind: ServiceAccount
  name: onload-operator-sa
---
apiVersion: onload.amd.com/v1alpha1
kind: Onload
metadata:
  labels:
    app.kubernetes.io/name: onload
    app.kubernetes.io/instance: onload-sample
    app.kubernetes.io/part-of: onload-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: onload-operator
  name: onload-sample
spec:
  serviceAccountName: onload-operator-sa
  selector:
    node-role.kubernetes.io/worker: ""
  onload:
    # Example image locations using openshift local image registry.
    kernelMappings:
      - regexp: '^.*\.x86_64$'
        kernelModuleImage: image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-module:v8.1.0-${KERNEL_FULL_VERSION}
        sfc: {}
    userImage: image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-user:v8.1.0
    version: 8.1.0
    imagePullPolicy: Always
  devicePlugin:
    devicePluginImage: kitchen-sink.kube.test:5000/deviceplugin:latest
    imagePullPolicy: Always
