# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: onload.amd.com/v1alpha1
kind: Onload
metadata:
  labels:
    app.kubernetes.io/name: onload
    app.kubernetes.io/instance: onload-sample
    app.kubernetes.io/part-of: onload-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: onload-operator
  name: onload-sample
spec:
  foo: bar
