//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildArg) DeepCopyInto(out *BuildArg) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildArg.
func (in *BuildArg) DeepCopy() *BuildArg {
	if in == nil {
		return nil
	}
	out := new(BuildArg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginSpec) DeepCopyInto(out *DevicePluginSpec) {
	*out = *in
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int)
		**out = **in
	}
	if in.SetPreload != nil {
		in, out := &in.SetPreload, &out.SetPreload
		*out = new(bool)
		**out = **in
	}
	if in.MountOnload != nil {
		in, out := &in.MountOnload, &out.MountOnload
		*out = new(bool)
		**out = **in
	}
	if in.HostOnloadPath != nil {
		in, out := &in.HostOnloadPath, &out.HostOnloadPath
		*out = new(string)
		**out = **in
	}
	if in.BaseMountPath != nil {
		in, out := &in.BaseMountPath, &out.BaseMountPath
		*out = new(string)
		**out = **in
	}
	if in.BinMountPath != nil {
		in, out := &in.BinMountPath, &out.BinMountPath
		*out = new(string)
		**out = **in
	}
	if in.LibMountPath != nil {
		in, out := &in.LibMountPath, &out.LibMountPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginSpec.
func (in *DevicePluginSpec) DeepCopy() *DevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginStatus) DeepCopyInto(out *DevicePluginStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginStatus.
func (in *DevicePluginStatus) DeepCopy() *DevicePluginStatus {
	if in == nil {
		return nil
	}
	out := new(DevicePluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Onload) DeepCopyInto(out *Onload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Onload.
func (in *Onload) DeepCopy() *Onload {
	if in == nil {
		return nil
	}
	out := new(Onload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Onload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnloadKernelBuild) DeepCopyInto(out *OnloadKernelBuild) {
	*out = *in
	if in.BuildArgs != nil {
		in, out := &in.BuildArgs, &out.BuildArgs
		*out = make([]BuildArg, len(*in))
		copy(*out, *in)
	}
	if in.DockerfileConfigMap != nil {
		in, out := &in.DockerfileConfigMap, &out.DockerfileConfigMap
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnloadKernelBuild.
func (in *OnloadKernelBuild) DeepCopy() *OnloadKernelBuild {
	if in == nil {
		return nil
	}
	out := new(OnloadKernelBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnloadKernelMapping) DeepCopyInto(out *OnloadKernelMapping) {
	*out = *in
	if in.SFC != nil {
		in, out := &in.SFC, &out.SFC
		*out = new(SFCSpec)
		**out = **in
	}
	if in.Build != nil {
		in, out := &in.Build, &out.Build
		*out = new(OnloadKernelBuild)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnloadKernelMapping.
func (in *OnloadKernelMapping) DeepCopy() *OnloadKernelMapping {
	if in == nil {
		return nil
	}
	out := new(OnloadKernelMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnloadList) DeepCopyInto(out *OnloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Onload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnloadList.
func (in *OnloadList) DeepCopy() *OnloadList {
	if in == nil {
		return nil
	}
	out := new(OnloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OnloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnloadSpec) DeepCopyInto(out *OnloadSpec) {
	*out = *in
	if in.KernelMappings != nil {
		in, out := &in.KernelMappings, &out.KernelMappings
		*out = make([]OnloadKernelMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnloadSpec.
func (in *OnloadSpec) DeepCopy() *OnloadSpec {
	if in == nil {
		return nil
	}
	out := new(OnloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnloadStatus) DeepCopyInto(out *OnloadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnloadStatus.
func (in *OnloadStatus) DeepCopy() *OnloadStatus {
	if in == nil {
		return nil
	}
	out := new(OnloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SFCSpec) DeepCopyInto(out *SFCSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SFCSpec.
func (in *SFCSpec) DeepCopy() *SFCSpec {
	if in == nil {
		return nil
	}
	out := new(SFCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spec) DeepCopyInto(out *Spec) {
	*out = *in
	in.Onload.DeepCopyInto(&out.Onload)
	in.DevicePlugin.DeepCopyInto(&out.DevicePlugin)
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spec.
func (in *Spec) DeepCopy() *Spec {
	if in == nil {
		return nil
	}
	out := new(Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Onload = in.Onload
	out.DevicePlugin = in.DevicePlugin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}
