# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: onload-sfnettest
  namespace: default
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: onload-sfnettest
  namespace: default
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    dockerfile: |
      FROM registry.redhat.io/ubi8/ubi-init
      ARG SFNETTEST_VERSION

      RUN dnf install -y git make findutils gcc  # CNS-sfnettest build time
      RUN dnf install -y pciutils                # (Optional) sfnt-pingpong runtime

      WORKDIR /build/
      ADD https://github.com/Xilinx-CNS/cns-sfnettest/archive/refs/tags/${SFNETTEST_VERSION}.tar.gz cns-sfnettest.tar.gz
      RUN mkdir -p /build/cns-sfnettest
      RUN tar xzf cns-sfnettest.tar.gz -C /build/cns-sfnettest --strip-components=1

      WORKDIR /build/cns-sfnettest/src
      RUN make

      USER 1001

  strategy:
    dockerStrategy:
      buildArgs:
      - name: SFNETTEST_VERSION
        value: "sfnettest-1.6.0-rc1"
  output:
    to:
      kind: ImageStreamTag
      name: onload-sfnettest:sfnettest-1.6.0-rc1
---
apiVersion: v1
kind: Pod
metadata:
  name: onload-sfnettest-server
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-sf0
spec:
  restartPolicy: Always
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: onload-sfnettest-server
    image: image-registry.openshift-image-registry.svc:5000/default/onload-sfnettest:sfnettest-1.6.0-rc1
    imagePullPolicy: Always
    command:
    - /build/cns-sfnettest/src/sfnt-pingpong
    resources:
      limits:
        amd.com/onload: 1
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  nodeName: compute-0
---
apiVersion: v1
kind: Pod
metadata:
  name: onload-sfnettest-client
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-sf0
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: onload-sfnettest-client
    image: image-registry.openshift-image-registry.svc:5000/default/onload-sfnettest:sfnettest-1.6.0-rc1
    imagePullPolicy: Always
    command:
    - /sbin/init
    resources:
      limits:
        amd.com/onload: 1
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  nodeName: compute-1
