# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../sfnettest/deploy/

configMapGenerator:
- name: onload-throughput-base-profile
  envs:
  - throughput-base.conf

patchesStrategicMerge:
- patch-add-configmap.yaml
