# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
nameReference:
- kind: ConfigMap
  fieldSpecs:
  - path: spec/onload/kernelMappings/build/dockerfileConfigMap
    kind: Onload

images:
- path: spec/onload/userImage
  kind: Onload
- path: spec/onload/kernelMappings/kernelModuleImage
  kind: Onload
- path: spec/onload/kernelMappings/build/buildArgs/value
  kind: Onload
