# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onload-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onload-operator-role
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onload-operator-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onload-operator-role
subjects:
- kind: ServiceAccount
  name: onload-operator-sa
---
apiVersion: onload.amd.com/v1alpha1
kind: Onload
metadata:
  name: onload
spec:
  serviceAccountName: onload-operator-sa
  selector:
    node-role.kubernetes.io/worker: ""
  onload:
    kernelMappings: []
    userImage: onload/onload-user
    version:
    imagePullPolicy: Always
  devicePlugin:
    devicePluginImage: onload/onload-device-plugin:3.0.0
    imagePullPolicy: Always
    # Limit number of pods that can request Onload on a node
    #maxPodsPerNode: 100
    # Uncomment to select whether LD_PRELOAD should be set by the device plugin
    # preload: true
