# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: v1
kind: Namespace
metadata:
  name: onload-user
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: onload-user
  name: onload-user
  namespace: onload-user
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: onload-user
  name: onload-user
  namespace: onload-user
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    dockerfile: (placeholder)
  strategy:
    dockerStrategy:
      buildArgs:
      - name: ONLOAD_BUILD_PARAMS
        value:
  output:
    to:
      kind: ImageStreamTag
      name: onload-user:latest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:image-puller
  namespace: onload-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
