# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: onload-user
  name: onload-user
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    dockerfile: (placeholder)
  strategy:
    dockerStrategy:
      buildArgs:
      - name: ONLOAD_BUILD_PARAMS
        value:
      - name: ONLOAD_VERSION
        value: 27b38261cfc394012413ee6cbeef8f1ae781489c
  output:
    to:
      kind: ImageStreamTag
      name: onload-user:git27b3826
      namespace: onload-clusterlocal
