# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- buildconfig.yaml

configMapGenerator:
- name: onload-user-dockerfile
  files:
  - dockerfile=Dockerfile

vars:
- name: ONLOAD_DOCKERFILE
  objref:
    kind: ConfigMap
    name: onload-user-dockerfile
    apiVersion: v1
  fieldref:
    fieldpath:
      data.dockerfile

configurations:
- bc-dockerfile-varref.yaml
