# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onload-cplane-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onload-cplane-role
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onload-cplane-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onload-cplane-role
subjects:
- kind: ServiceAccount
  name: onload-cplane-sa
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: onload-cplane-ds
spec:
  selector:
    matchLabels:
      name: onload-cplane-ds
  template:
    metadata:
      labels:
        name: onload-cplane-ds
    spec:
      serviceAccount: onload-cplane-sa
      serviceAccountName: onload-cplane-sa
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: onload-cplane
        image: image-registry.openshift-image-registry.svc:5000/onload-clusterlocal/onload-cplane:latest
        imagePullPolicy: Always
        command: ["/usr/bin/onload-cplane-container-utility"]
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
