# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
resources:
- ../base

patches:

# Onload KMM debug build
- target:
    kind: Module
    name: onload-module
  patch: |
    - op: replace
      path: /spec/moduleLoader/container/kernelMappings/0/build/buildArgs/0/value
      value: --debug

# Onload userspace debug build
- target:
    kind: BuildConfig
    name: onload-user
  patch: |
    - op: add
      path: /spec/strategy/dockerStrategy/buildArgs/0/value
      value: --debug
