# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: onload-device-plugin
  name: onload-device-plugin
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: onload-user:git27b3826
          namespace: onload-artifacts
  source:
    dockerfile: (placeholder)

  strategy:
    dockerStrategy:
      buildArgs:
  output:
    to:
      kind: ImageStreamTag
      name: onload-device-plugin:latest
      namespace: onload-artifacts
