# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onload-device-plugin-sa
  namespace: onload-device-plugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onload-device-plugin-role
  namespace: onload-device-plugin
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onload-device-plugin-rb
  namespace: onload-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onload-device-plugin-role
subjects:
- kind: ServiceAccount
  name: onload-device-plugin-sa
userNames:
- system:serviceaccount:onload-device-plugin:onload-device-plugin
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: onload-device-plugin-ds
  namespace: onload-device-plugin
spec:
  selector:
    matchLabels:
      app: onload-device-plugin-ds
  template:
    metadata:
      labels:
        app: onload-device-plugin-ds
    spec:
      # The service account is needed so that the pod can mount a volume from
      # the host.
      serviceAccount: onload-device-plugin-sa
      serviceAccountName: onload-device-plugin-sa
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/onload-device-plugin/onload-device-plugin:latest
        name: onload-device-plugin
        imagePullPolicy: Always
        command: ["/usr/bin/onload-plugin"]
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /var/lib/kubelet/device-plugins
            name: kubelet-socket
      volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
          name: kubelet-socket
      nodeSelector:
        node-role.kubernetes.io/worker: ""
