# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: onload-module
spec:
  moduleLoader:
    container:
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: www.example.com/onload-module:enterpriseonload-8.1.0.2-${KERNEL_FULL_VERSION}
          build:
