# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2023 Advanced Micro Devices, Inc.
apiVersion: v1
kind: Namespace
metadata:
  name: onload-artifacts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:image-puller
  namespace: onload-artifacts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: onload-user
  namespace: onload-artifacts
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: onload-device-plugin
  namespace: onload-artifacts
spec: {}
