# SPDX-License-Identifier: MIT
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc.
name: "Static Analysis"

on:
  workflow_dispatch:
    inputs:
      lint_codebase:
        description: Lint all files instead of changed
        default: false
        required: true
        type: boolean
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.go'
      - go.mod
  push:
    branches: [master]
    paths-ignore:
      - '**.go'
      - go.mod

env:
  lint-all: ${{ github.event_name == 'workflow_dispatch' && inputs.lint_codebase }}
jobs:
  lint-general:
    name: Super Linter
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # super-linter req

    - name: Super Linter
      uses: super-linter/super-linter/slim@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # super-linter is designed around linting changed files only,
        # which is fast. Optionally, lint all files.
        VALIDATE_ALL_CODEBASE: ${{ env.lint-all }}
        VALIDATE_GO: false
        FILTER_REGEX_EXCLUDE: '(.*/ContainerFileNotice|.*_patch\.yaml)'
        KUBERNETES_KUBECONFORM_OPTIONS: --ignore-missing-schemas
        IGNORE_GITIGNORED_FILES: true
        ERROR_ON_MISSING_EXEC_BIT: true
        LINTER_RULES_PATH: /
        YAML_CONFIG_FILE: .yamllint.yml
